repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
#    - id: ruff
#      args: [check --fix --select F --select W --select B --select C4 --select Q --select I --show-fixes]
    - id: ruff-format
