version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  pg_admin:
    container_name: pg4_admin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"