services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    profiles:
      - postgres

  pg_admin:
    container_name: pg4_admin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    profiles:
      - db_admin

  fastapi:
    container_name: fastapi
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_started
    profiles:
      - fast_api
