services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    profiles:
      - db
  pg_admin:
    container_name: pg4_admin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    profiles:
      - db_admin
    depends_on:
      - db
  fastapi:
    container_name: fastapi
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    profiles:
      - fast_api
