name: API TEST

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_fastapi_project:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout FastAPI Example
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.12

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests -n 4